### ISSUE TITLE
nintedo switch OLED CFW 16.0.0 Atmosphere 1.5.1 crashes while using Edizon overlay

### ISSUE THREAD

**Issue by S0L1DB** [proferabg/EdiZon-Overlay#14]
![Knipsel](https://user-images.githubusercontent.com/128427740/226469790-7179ae24-3361-45be-bf8a-336b25683371.PNG)

When im enabling a cheat, this happens. im not the only person having this problem.

what i did:

- every overlay updated
- followed the NOTE
- updated teslamenu

nothing works, switch keeps crashing while enabling a cheat instantly. a new fix would be great.

**Comment by proferabg** [comment]
Please post your cheat file and what game and version you are running.

**Comment by proferabg** [comment]
[EdiZon-Overlay.zip](https://github.com/proferabg/EdiZon-Overlay/files/11028664/EdiZon-Overlay.zip)
Sorry. I was working on cleaning up the source and was going to push a bigger update. Here is a version with Blue highlights so if people make videos for this build, I will know.

**Comment by RetroMarioBros** [comment]
Thank you so much !
I'm going to try it!

**Comment by proferabg** [comment]
> 

I actually just changed the file again. Please redownload it and it should now say v1.0.5-beta. I made an edit to libtesla to see if the session exhaustion still happens.

**Comment by RetroMarioBros** [comment]
I'm testing in portable mode so far I haven't had any crashes.
when I get home I try in dock mode

**Comment by S0L1DB** [comment]
> I am having same issue but on regular switch v1 also did you play in docked or handheld.

i dont really use docked, always handheld mode, and yes crashes

**Comment by ELY3M** [comment]
it still crashing with your beta ovl and the official  tesla menu ovl.  

https://youtu.be/PV1iNzGghMU

[test-3-21-23.zip](https://github.com/proferabg/EdiZon-Overlay/files/11033594/test-3-21-23.zip)

**Comment by S0L1DB** [comment]
> Please post your cheat file and what game and version you are running.

im using house flipper cheats: https://github.com/ChanseyIsTheBest/NX-60FPS-RES-GFX-Cheats/blob/main/titles/0100CAE00EB02000/House%20Flipper.txt

im on CFW 16.0.0 atmosphere 1.5.1

**Comment by S0L1DB** [comment]
did you check?

**Comment by muxi1** [comment]
libtesla was fixed. Now there should be no more crashes in dock mode.

**Comment by proferabg** [comment]
> did you check?

I did check. The issue still persists.

> libtesla was fixed. Now there should be no more crashes in dock mode.

I pushed [v1.0.5](https://github.com/proferabg/EdiZon-Overlay/releases/tag/v1.0.5) to fix crashes from docked mode. The font system bug is still present.

I am going to close this issue as there is already an [existing issue](https://github.com/proferabg/EdiZon-Overlay/issues/12) for the same crashes.

**Comment by Skonikol** [comment]
My problem persisted on 1.0.5.
![IMG_5187](https://user-images.githubusercontent.com/5678237/229378467-618bd600-a5a2-4c89-96e9-516d904ef1a7.JPG)
